### ISSUE TITLE
Possibility to send reports to one launch

### ISSUE THREAD

**Issue by fasterfish** [reportportal/agent-net-specflow#12]
I have the need to send reports from different OS and test runs to the same launch in the report portal.
Could you implement this possibility?

**Comment by aliaksandrbasau** [comment]
This is no so easy task but it's doable. Here is how we do it on my project:
1. CI server creates a RP launch and saves the launch id to app.config of test binaries.
2. Test binaries are copied to VMs and run there.
3. The tests start and see that there is launch id in app.config and don't create a new launch - they re-use the existing one. Also they don't close it once they are done.
```c#
[BeforeTestRun(Order = -30000)]
public static void BeforeTestRunPart()
{
	ReportPortalAddin.BeforeRunStarted += ReportPortalAddin_BeforeRunStarted;
	ReportPortalAddin.BeforeRunFinished += ReportPortalAddin_BeforeRunFinished;
}

public static void ReportPortalAddin_BeforeRunStarted(object sender, RunStartedEventArgs e)
{
	var launchId = SettingsManager.CommonSettings.ReportPortalLaunchId;
	if (launchId.IsNullOrEmpty() == false)
	{
		e.Canceled = true;
		Bridge.Context.LaunchId = launchId;
	}
}

public static void ReportPortalAddin_BeforeRunFinished(object sender, RunFinishedEventArgs e)
{
	var launchId = SettingsManager.CommonSettings.ReportPortalLaunchId;
	if (launchId.IsNullOrEmpty() == false)
	{
		e.Canceled = true;
	}
}
```
4. When all tests run, CI server closes the RP launch.

**Comment by DzmitryHumianiuk** [comment]
@aliaksandrbasau could you also copy it into created question:
https://stackoverflow.com/questions/44395799/possibility-to-send-reports-to-one-launch-in-reportportal-for-net-specflow

**Comment by aliaksandrbasau** [comment]
@DzmitryHumianiuk I will.

**Comment by fasterfish** [comment]
@aliaksandrbasau when I run a single test, the results do not fall on the reportportal.
What versions of Nuget packages (Specflow, Unit Test Runner, ReportPortal) do you use?

**Comment by aliaksandrbasau** [comment]
I am using SpecFlow 2.2.0-preview20161020, NUnit 2.6.4, log4net 1.2.10 and RP integration library from https://github.com/reportportal/example-net-specflow-nunit2-log4net.
