### ISSUE TITLE
Hook attributes work incorrectly

### ISSUE THREAD

**Issue by fasterfish** [reportportal/agent-net-specflow#13]
For example, I want to use the[ following hook attributes](https://github.com/techtalk/SpecFlow/wiki/Hooks).

I use the following versions of the components:
ReportPortal.Client 1.2.7
ReportPortal.NLog 1.1.5-beta-2
ReportPortal.Shared 1.2.2-beta-1
ReportPortal.SpecFlow 1.2.0-beta-4
SpecFlow 2.1.0
NUnit 3.7.1
NUnit.Console 3.6.1
NLog 4.4.10

After running the tests in the console, I see the usual logging (watch console.txt).
But while messages from some hooks (Before Feature) do not get on the report portal (watch portal.png).
The console output, the report portal screenshot, the feature file and test steps are in the [artefacts.zip](https://github.com/reportportal/agent-net-specflow/files/1055900/artefacts.zip).

**Comment by aliaksandrbasau** [comment]
I don't think it's feasible to see messages from Before/After Feature/Run hooks on RP as the test item where they should be logged doesn't not exist at that point.
It all comes down to the limitation/feature that only test items can have log messages (but not test suites).
Logger libraries will see that Bridge.Context.TestId is null and will not even try to log the messages.

Please let me know if it answers your question.

**Comment by fasterfish** [comment]
@aliaksandrbasau, this answered only a part of my question. And what about the BeforeScenario hook?
You can see an example, I tried to use all possible hooks in it.

Nevertheless, I would like to be able to log the steps before scenario and before the "given" step.

**Comment by aliaksandrbasau** [comment]
The issue with BeforeScenario will be fixed in the next release (or in the current beta release).
The second issue is just a result of log items created at the very same time. That's why they have random and weird order.
