### ISSUE TITLE
Agent doesn't work with Specflow 2.2

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/agent-net-specflow#16]
OneTimeSetUp: System.TypeLoadException : Could not load type 'TechTalk.SpecFlow.Configuration.RuntimeConfiguration' from assembly 'TechTalk.SpecFlow, Version=2.2.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41'.

**Comment by nvborisenko** [comment]
@aliaksandrbasau Alex, is it reproducible for you too?

**Comment by aliaksandrbasau** [comment]
@nvborisenko Yep. Constructor parameters of BindingInvoker were changes and it caused an error on runtime. I prepared a pull request #17  that should resolve the issue/
