### ISSUE TITLE
results are not complete

### ISSUE THREAD

**Issue by nabsofken** [reportportal/agent-net-specflow#19]
I am running specflow tests but the results generated are very basic. It only shows the Given when then steps but no information regarding the BeforeScenario hooks etc and the failing step is not highlighted red. below is a screenshot. Anyway I could improve this? I am using Bridge.LogMessage to insert the screenshot in the result. 
![rp](https://user-images.githubusercontent.com/1247761/28507195-f2c96342-6ffe-11e7-9432-d6065c26fd96.jpeg)

using specflow 2.2 and using nunit 3.7 to run the tests

**Comment by aliaksandrbasau** [comment]
In order to see the messages logged from the hooks and tests you need to use one of logger libraries for .net ([logger-net-*](https://github.com/reportportal?utf8=%E2%9C%93&q=logger-net-)).
The failed step will not be highlighted. Only messages logged with Error log level will be highlighted red.
