### ISSUE TITLE
Screenshot on scenario error

### ISSUE THREAD

**Issue by mbnovick** [reportportal/agent-net-specflow#30]
I'd like to use  `ReportPortal.SpecFlowPlugin`, but add a log item with an attached screenshot if there is a scenario error. Is there any way to do this?

`ReportPortalHooks.AfterScenario` handles the case where `ScenarioContext.ScenarioExecutionStatus` is `ScenarioExecutionStatus.TestError`, and adds a new log item, but it does not include a screenshot. I'd like to be able to add a log item containing the screenshot when there's an error.

I could write my own `AfterScenario` hook which would run before ReportPortalHooks's hook, and add log item with screenshot there, but that would mean logging twice, first in the new hook, then in the hook in the plugin. This is wasteful since there would be two log items when I really want just one.

I could write my own `AfterScenario` hook which would add log item with screenshot, then modify scenario context so that `ReportPortalHooks.AfterScenario` does not do anything. It looks like I'd have to copy much of the logic from `ReportPortalHooks.AfterScenario` and put it the new hook. This would be wasteful, and I'd have to make changes to my hook if future versions of the plugin change the implementation of `AfterScenario` hook.

Is there any simple way I can add log item containing screenshot when scenario execution fails?

**Comment by nvborisenko** [comment]
Added an example: https://github.com/reportportal/example-net-specflow/commit/bd125b856b3199621dfe60147f3e8f9eb769cbc1
Be noticed that you are required to save this image to file in this example. But there are other `formatters` such as `base64`. The list of available formatters: https://github.com/reportportal/commons-net/tree/master/ReportPortal.Shared/LogFormatters
If you need more formatters, please create a separate issue to continue our discussion.

**Comment by mbnovick** [comment]
The  example and the information on log formatters provided by @nvborisenko looks like it will be useful in the future, but it does not look so relevant for my needs here. If I follow this suggestion, I'll get two log items for an unsuccessful scenario: one from the call to `Bridge.LogMessage` and one from the `AfterScenario `hook in `ReportPortalHooks`. I only want to see one message. Is there some way I can modify the log item created by the existing hook used by plugin? I could create my own log item and somehow prevent plugin hook from creating extra log item. I could create plugin log item as is, and later add attachment after scenario is finished if that's possible. Maybe there are other solutions, but having 2 log items created is not my preferred solution.

**Comment by nvborisenko** [comment]
Cannot understand which exact 2 log items you have. I see 
![screenshot_1](https://user-images.githubusercontent.com/22616990/45023006-41035b00-b03e-11e8-807e-2710c78b3b30.png) It seems good to me.
Could you please describe what you want to see on RP?

**Comment by mbnovick** [comment]
What you saw in RP illustrates the problem I'm talking about. You have two log items at the end: one of them contains a picture of a cat and the other shows the stack trace. I only want one log item. It should contain the stack trace and include a screenshot of my desktop at the top the error occurred. I don't know how I could create only one log item, which contains attached screenshot in this case. Is it possible to do with existing plugin or possibly with some small changes that could be made to the SpecFlow plugin?

**Comment by nvborisenko** [comment]
Yes, it is possible. Give me some time, I will release a new version of plugin where this red log message can be canceled by your customization.
The idea is your will subscribe on `OnBeforeScenarioFinished` event, set `e.Canceled = true`, and now you are responsible how to finish test item.

**Comment by nvborisenko** [comment]
Now with v1.2.5 you can do something like
```csharp
ReportPortalAddin.BeforeScenarioFinished += ReportPortalAddin_BeforeScenarioFinished;

// implementation
private static void ReportPortalAddin_BeforeScenarioFinished(object sender, TestItemFinishedEventArgs e)
        {
            e.Canceled = true;

            // now I am responsible how to finish test item

            if (e.TestItem.Status == ReportPortal.Client.Models.Status.Failed)
            {
                e.TestReporter.Log(new ReportPortal.Client.Requests.AddLogItemRequest
                {
                    Time = DateTime.UtcNow,
                    Level = ReportPortal.Client.Models.LogLevel.Error,
                    Text = "My failure message",
                    Attach = new ReportPortal.Client.Models.Attach
                    {
                        Name = "Screenshot",
                        MimeType = "images/png",
                        Data = imageBytes //byte[]
                    }
                });
            }

            e.TestReporter.Finish(e.TestItem);
        }
```

**Comment by nvborisenko** [comment]
@mbnovick is it resolving your issue?

**Comment by mbnovick** [comment]
The suggestion mentioned by @nvborisenko seems to do most of what I want. One minor point: what if I added handlers for `ReportPortalAddin.AfterScenarioFinished` event? It looks like the handlers won't be invoked if I call `e.TestReporter.Finish` on my own. Is there anything I could do to make sure the handlers would be invoked after Finish?

**Comment by nvborisenko** [comment]
Right, it is your responsibility.
```csharp
ReportPortalAddin.AfterScenarioFinished?.Invoke(this, e);
```

**Comment by mbnovick** [comment]
The problem is that you can't raise an event of a class from a different class in C#. See [https://stackoverflow.com/questions/4378339/raise-an-event-of-a-class-from-a-different-class-in-c-sharp](url) for instance. Some workarounds are described there, such as getting around the type safety of .NET or extensively using reflection.
If I try to add the code you suggested, I get an error message:
`The event 'ReportPortalAddin.AfterScenarioFinished' can only appear on the left hand side of += or -=
The event 'AfterScenarioFinished' can only appear on the left hand side of += or -=`
Is there some other way I can make sure AfterScenarioFinished event is handled?

**Comment by nvborisenko** [comment]
@mbnovick does it work for you?

**Comment by nvborisenko** [comment]
Closing this issue. Please create separate issue in https://github.com/reportportal/commons-net repository if you don't use specflow.
