### ISSUE TITLE
GPL 3.0 License for .net agents

### ISSUE THREAD

**Issue by schoi1** [reportportal/agent-net-specflow#37]
Our company does not accept GPL license under any circumstances. So this license issue prevents us from using ReportPortal.

On this [GitHub issue](https://github.com/reportportal/reportportal/issues/293), Dzmitry noted that they will re-license all agents and integrations under Apache 2.0 license.

However, I noticed that only Java client has been updated and all other agents are still GPL license. Is there any plan to change to Apache 2.0 for other agents?

**Comment by nvborisenko** [comment]
@DzmitryHumianiuk, is MIT license ok?

**Comment by DzmitryHumianiuk** [comment]
@schoi1, we just need a time to complete it.
@nvborisenko will start to relicense .net related repos under Apache2.0.
2-3 days to complete

**Comment by nvborisenko** [comment]
Changed to Apache2.0
