### ISSUE TITLE
Skipped steps are not shown in a report

### ISSUE THREAD

**Issue by mefateah** [reportportal/agent-net-specflow#38]
For some reason after upgrading NUnit and ReportPortal related libs:
ReportPortal.Client
ReportPortal.NLog
ReportPortal.Shared
ReportPortal.SpecFlow
I faced that skipped steps are not shown in a test report.
For example I run the following scenario from example project:
```
Scenario: Add three numbers
	Given I have entered 3 into the calculator
	And I have entered 7 into the calculator
	And I have entered 8 into the calculator
	When I press add
	Then the result should be 18 on the screen
```
and made the scenario to fail in 'And I have entered 7 into the calculator' step
then I don't see all steps after the failed one
![image](https://user-images.githubusercontent.com/22494175/51745165-17ad9f00-20b3-11e9-93a3-60e6dbf2c6eb.png)
but in a previous version I've seen them as skipped

**Comment by Konorova1991** [comment]
> For some reason after upgrading NUnit and ReportPortal related libs:
> ReportPortal.Client
> ReportPortal.NLog
> ReportPortal.Shared
> ReportPortal.SpecFlow
> I faced that skipped steps are not shown in a test report.
> For example I run the following scenario from example project:
> 
> ```
> Scenario: Add three numbers
> 	Given I have entered 3 into the calculator
> 	And I have entered 7 into the calculator
> 	And I have entered 8 into the calculator
> 	When I press add
> 	Then the result should be 18 on the screen
> ```
> and made the scenario to fail in 'And I have entered 7 into the calculator' step
> then I don't see all steps after the failed one
> ![image](https://user-images.githubusercontent.com/22494175/51745165-17ad9f00-20b3-11e9-93a3-60e6dbf2c6eb.png)
> but in a previous version I've seen them as skipped

I have the same issue using NUnit 3. Could you receive this problem, please?

**Comment by nvborisenko** [comment]
What was your previous version of `ReportPortal.SpecFlow` package you didn't meet this issue with?

**Comment by mefateah** [comment]
@nvborisenko It worked with the following lib packages versions:
"NUnit" version="2.6.4"
"ReportPortal.Client" version="1.2.3"
"ReportPortal.NLog" version="1.1.8"
"ReportPortal.Shared" version="1.4.1"
"ReportPortal.SpecFlow" version="1.2.1"
"SpecFlow" version="2.1.0"

**Comment by nvborisenko** [comment]
#49 new `CucucmberMessages` might help.
