### ISSUE TITLE
Tags from SpecFlow examples aren't added

### ISSUE THREAD

**Issue by fasterfish** [reportportal/agent-net-specflow#4]
When I run the following scenario from Nunit console runner:

```
Feature: Feature1
	In order to avoid silly mistakes
	As a math idiot
	I want to be told the sum of two numbers

@mytag
Scenario Outline: Add two numbers
	Given I have entered <num1> into the calculator
	And I have entered <num2> into the calculator
	When I press add
	Then the result should be <result> on the screen

@positive
Examples:
| num1 | num2 | result	|
| 2    | 3    | 5	|

@negative
Examples:
| num1 | num2 | result |
| -999  | 999  | 0    |
```
For each example at the report portal I see only scenario tags:
![screenshot_1](https://cloud.githubusercontent.com/assets/18389889/21212297/2d2fa21c-c2ad-11e6-8034-7cb254da079b.png)
but specified examples tags aren't exists.

Test result xml in attachment:
[TestResult.txt](https://github.com/reportportal/agent-net-specflow/files/653817/TestResult.txt)

**Comment by aliaksandrbasau** [comment]
There is known issue in SpecFlow 2.x (https://github.com/techtalk/SpecFlow/issues/718). You can update specflow to 2.2 pre-release version (it's available on NuGet) and it will be fixed.

**Comment by nvborisenko** [comment]
@aliaksandrbasau could you please close this issue when impediment is resolved? Thx.

**Comment by fasterfish** [comment]
No problem, thank u too.
