### ISSUE TITLE
Both nunit & SpecFlow launch for a single run in .NET but not in .NET Core

### ISSUE THREAD

**Issue by MithunDavid** [reportportal/agent-net-specflow#47]
We are seeing both Nunit and Specflow launch for a single run in .NET. But for .NET Core, Its working correctly. Only SpecFlow launch shows up here.

**Comment by nvborisenko** [comment]
Seems you have installed several agents: **ReportPortal.NUnit** and **ReportPortal.SpecFlow**. Choose one which you like more.
If it doesn't work for you, please describe the issue with more details.

**Comment by MithunDavid** [comment]
Yes. ReportPortal Nunit reference was pulling from framework. Thanks for pointing it. Issue is fixed.
