### ISSUE TITLE
Specflow agent 1.5.1 and ReportPortal v5

### ISSUE THREAD

**Issue by gkalnytskyi** [reportportal/agent-net-specflow#48]
My company is evaluating ReportPortal and recently upgraded the installation to ReportPortal 5 (beta). The issue at the moment is that I cannot log any data to ReportPortal 5, even though the agent configuration hasn't changed much. Also, no "ReportPortal.log" file is created when I run tests to allow me to understand the issue.

Nuget packages:
- ReportPortal.Client 2.1.14
- ReportPortal.Shared 2.3.2
- ReportPortal.SpecFlow 1.5.1
- SpecFlow 2.4.1
- SpecFlow.NUnit 2.4.1

Config:

    {
      "$schema": "https://raw.githubusercontent.com/reportportal/agent-net-specflow/master/ReportPortal.SpecFlowPlugin/ReportPortal.config.schema",
      "enabled": true,
      "server": {
        "url": "${server uri}:8080/api/v1/",
        "project": "project_blah",
        "authentication": {
          "uuid": "5d655790-8084-4a61-afe0-b3096d01fe4e"
        }
      },
      "launch": {
        "name": "launch_name",
        "description": "acceptance_tests",
        "debugMode": true,
        "tags": []
      }
    }

**Comment by nvborisenko** [comment]
Known issue in beta https://github.com/reportportal/reportportal/issues/684

**Comment by gkalnytskyi** [comment]
And what about the absence of ReportPortal.log file?

**Comment by nvborisenko** [comment]
It might be issue, but I guess issue is in nuget packages. I see you installed the latest Shared package, while RP.SpecFlow is still old. Please resolve dependencies. Example: RP.SpecFlow requires Shared v2.1.4, which requires RP.Client 2.1.8. Please try these exact versions.

Actually we didn't introduce constraints in nuget packages. Your case is good to think about it.

**Comment by gkalnytskyi** [comment]
Hello @nvborisenko ,  I have downgraded the packages and reran the tests, and still no ReportPortal.log file was generated.

**Comment by nvborisenko** [comment]
Please prepare simple test project to reproduce the issue. It will be very useful in figuring out what is wrong.

**Comment by nvborisenko** [comment]
@gkalnytskyi, closing it due inactivity, feel free to reopen if the issue is still reproducible.
