### ISSUE TITLE
Example of adding feature description

### ISSUE THREAD

**Issue by winstondz** [reportportal/agent-net-specflow#57]
I looked through the example agent-net-specflow and I see that the feature description gets added in report portal. Do I have to write something in the customization file or in the hooks for this. If so is there an example? I have both specflow as well as normal nunit tests and if possible want to use just the nunit one (instead of both), but also have the specflow feature description printed? Is this possible with the current implementation?

**Comment by nvborisenko** [comment]
Closing due inactivity, feel free to reopen.
