### ISSUE TITLE
Full Title in Case of scenario outline not showing. [Question]

### ISSUE THREAD

**Issue by Jaskaran121** [reportportal/agent-net-specflow#58]
Feature: CalculatorFeature
	 In order to avoid silly mistakes 
	As a math idiot
	I want to be told the sum of two numbers

@BasePage
Scenario Outline: Basepage is Calculator
	When I navigate to the Calculator page

Scenarios: 
| Browser |
| Chrome  |
| IE	        |

**Right now i am not able to see full scenario name, like it shows in specflow runner.**

![test](https://user-images.githubusercontent.com/35613378/97496271-1c198280-193f-11eb-8940-14a1b1dffb0b.PNG)

**Though i can see in report portal more info option like**
![Inkedtest2_LI](https://user-images.githubusercontent.com/35613378/97496942-1cfee400-1940-11eb-86c1-6500c60b734b.jpg)

**Is it possible to see the full scnerio title in the main page itself , rather clicking on more info...here:-**

![test1](https://user-images.githubusercontent.com/35613378/97496531-71559400-193f-11eb-8839-1d33a6fbaf80.PNG)

If this possible by configuring something can you please let me know... thankx

**Comment by nvborisenko** [comment]
Thanks for point at this behavior. I don't mind that agent will put scenario outline parameters as item description.

@Jaskaran121 It will be implemented in the next agent release.

**Comment by nvborisenko** [comment]
@Jaskaran121 please review the following suggestion

![image](https://user-images.githubusercontent.com/22616990/97624135-b957e200-1a37-11eb-80af-9f2a82aeb6a1.png)

Table represents scenario outline examples. `a` and `b` are parameters.

**Comment by Jaskaran121** [comment]
@nrodiontsev2 Yes this will work....though really fast work I was myself thinking of creating a PR for this. ;)
Sorry for asking this question so early... but when do you guys are planning to release this?

**Comment by nvborisenko** [comment]
Now. v3.0.1 is available (give 10 mins for indexing).
