### ISSUE TITLE
Specflow result

### ISSUE THREAD

**Issue by santhosh-James** [reportportal/agent-net-specflow#62]
Right now Reportportal shows the feature file in report and when an exception happens it create another row in the report to show the test output. 

I want to log some additional information to the report. I want to do it from the [After Scenario] in specflow hook. Is there a way that I can do it?

I tried Log.Trace() in Afterscenario but it is not working consistently and only works if some exceptions happens

**Comment by nvborisenko** [comment]
> I tried Log.Trace() in Afterscenario but it is not working consistently and only works if some exceptions happens

You are doing right. I tried and see my log messages. Please add more details.
