### ISSUE TITLE
Report link

### ISSUE THREAD

**Issue by andrey-brovko** [reportportal/agent-net-specflow#73]
I would like to print the launch link. Could you please help me with that?

The link looks like this:
https://reportportal.ru/#superadmin_personal/launches/all/18c1004f-d66c-4217-9aac-5c95b317914a

`{URL}/ui/#{projectName}/launches/all/{launchUuid}`

I need to get values in curve brackets.

My code looks like this:

```
        [BeforeScenario]
        public void PrintReportPortalLaunchLink()
        {
            var launchUuid = ReportPortalAddin.GetScenarioTestReporter(_scenarioContext).LaunchReporter.Info.Uuid;
            TestContext.WriteLine($"https://reportportal.com/ui/#superadmin_personal/launches/all/{launchUuid}");
        }
```

The URL and the project name are hardcoded which is not good.

**Comment by nvborisenko** [comment]
It's already implemented in scope of https://github.com/reportportal/commons-net/issues/74, but not yet released.
