### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: Property 'Server:Authentication:Uuid' not found in the configuration

### ISSUE THREAD

**Issue by vladyslav-panasenko** [reportportal/agent-net-specflow#83]
Please add API key support.

Version: ReportPortal.SpecFlow 3.6.0 

Error: throw System.Collections.Generic.KeyNotFoundException: Property 'Server:Authentication:Uuid' not found in the configuration.

config
```json
  "enabled": true,
   "server": {
    "url": "url",
    "project": "project",
    "apiKey": "api_key"
  },
  "launch": {
    "name": "name",
    "description": "name",
    "debugMode": true,
    "tags": [ "QA" ],
    "attributes": ["QA"]
  }
```

Reason: [var uuid = Plugin.Config.GetValue<string>(ConfigurationPath.ServerAuthenticationUuid);](https://github.com/reportportal/agent-net-specflow/blob/57638d8868401b580cec328c88224085965a37b2/src/ReportPortal.SpecFlowPlugin/ReportPortalHooks.cs#L88)

Underline dotnet line supports API keys  - [HttpClientFactory](https://github.com/reportportal/client-dotnet/blob/08eddf1351eaa0f3c07ca968c2ea614a910acead/src/ReportPortal.Shared/Reporter/Http/HttpClientFactory.cs#L52)

All examples show a new approach with API key auth, whatever dotnet specflow agent does not support API key yet.

**Comment by nvborisenko** [comment]
@vladyslav-panasenko, fixed in v3.6.1, thanks for the report.
