### ISSUE TITLE
Retry not working correctly using vstest + specflow agent

### ISSUE THREAD

**Issue by heilwood** [reportportal/agent-net-specflow#85]
We are using retry mechanism in our azure pipelines with vstest task which should retry failed tests, but is not working correctly with specflow agent, instead of retrying failed tests vstest re-running all available tests and problems looks like in naming of tests using specflow agent, vstest selecting incorrect filter for specific test, instead of using name of test scenario + test scenario example, he using just feature name.

![image](https://github.com/user-attachments/assets/f6b08b6b-603f-4438-8e1f-199c69bcb3f2)

Output from azure pipeline (Check Test Case Filter):

`Failed tests: 1; Total tests: 20;
Total failed tests as returned by TCM: 1.
Found 1 filtered test case sources.
**************** Rerunning failed tests for Test run 2656682 *********************
Max attempts: 2; Current attempt: 1; Failed test cases threshold: 30; Failed test cases max limit: 0
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@C:\agent\_work\_temp\jlbvhts0s42.tmp"
Microsoft (R) Test Execution Command Line Tool Version 17.7.2 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.
vstest.console.exe /TestCaseFilter:"(FullyQualifiedName=Automation.Common.Addons.#()::Target:Chrome_PC_Functional/TestAssembly:Automation.Price)"`

Packages version:
![image](https://github.com/user-attachments/assets/e2889ce8-faff-4068-bbc0-1e5efe24f5ef)

Test Runner: SpecRun

**Comment by nvborisenko** [comment]
ReportPortal is not responsible for running tests, it is reporting test results. We cannot fix it.

I guess you should post new issue for VsTest repo or SpecRun.

**Comment by heilwood** [comment]
> ReportPortal is not responsible for running tests, it is reporting test results. We cannot fix it.
> 
> I guess you should post new issue for VsTest repo or SpecRun.

VStest re-running failed tests based on test name which present in logs, SpecFlow agent not responsible for logging? It can be that SpecFlow Agent logging incorrect names?

**Comment by nvborisenko** [comment]
> VStest re-running failed tests based on test name which present in logs

I hope it is just an assumption.

> SpecFlow agent not responsible for logging?

RP.SpecFlow does log nothing.

> It can be that SpecFlow Agent logging incorrect test names?

It logs nothing.

@heilwood please uninstall all RP NuGet packages, and if the issue remains reproducible - we dive deeper.

**Comment by heilwood** [comment]
you are right, problem is on runner side somewhere, thank you for your effort!
